name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '20'  # Latest Node version

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      - name: Setup Firebase Service Account
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > ./firebase-key.json

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ github.workspace }}/firebase-key.json"
        run: firebase deploy --only hosting --project squadvertex24